### ISSUE TITLE
'Name or service not known' error when attempting to login.

### ISSUE THREAD

**Issue by djorgesen** [simple-salesforce/simple-salesforce#65] opened 2015-05-29 15:34 UTC
Receive this error when attempting to login either with Salesforce.login() or SalesforceLogin()

This is when passing in user, password, token, and sandbox = True.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/simple_salesforce/login.py", line 106, in SalesforceLogin
    proxies=kwargs.get('proxies', None))
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by demianbrecht** [comment] 2016-06-14 04:22
Closing assuming this was resolved (seems like a system issue). Please reopen if you're still running into it.

**Closed by demianbrecht** 2016-06-14 04:22 UTC

**Comment by jtbaird** [comment] 2021-06-28 19:58
Hey there. I'm getting the same issue when trying to connect with a JWT key file. Like so:

`conn = sf.Salesforce(username=user, instance_url='https://<my company's salesforce url>.com', domain='<my companies salesforce domain>.com', consumer_key=<our key>, privatekey_file=<our private key file>)`

The keys are not the issue as I'm using the exact same ones to authenticate with salesforce via scripted pipeline. The specific error is:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host=<my company's salesforce domain>, port=443): Max retries exceeded with url: /services/oath2/token (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at <some hash code>>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

I have also tried running the urllib3 command from our pipeline that is failing in the above error, and it runs successfully. Here's how i'm running that command:

`conn = urllib3.connectionpool.HTTPSConnectionPool(host='<my company's domain>', port=443)`

Any advice here would be much appreciated.
