### ISSUE TITLE
Doesn't seem to work on ARM arch

### ISSUE THREAD

**Issue by geekpete** [simple-salesforce/simple-salesforce#126] opened 2016-08-05 05:55 UTC
```
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes
 -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat 
-Werror=format-security -fPIC -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi
 -I/usr/include/python2.7 -c c/_cffi_backend.c 
-o build/temp.linux-armv7l-2.7/c/_cffi_backend.o
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

Anything that needs to be done to get this installing on arm architecture?

**Comment by nickcatal** [comment] 2016-08-12 03:54
I believe you need `libffi-dev` on your machine. That library provides the `ffi.h` file.

I don't have an ARM machine to reproduce this, but I've run into the "no ffi.h" problem before on other projects. Installing that package seems to fix it.

**Comment by demianbrecht** [comment] 2016-12-01 04:34
Closing due to lack of movement (assuming that `libffi-dev` @nickcatal recommended worked)

**Closed by demianbrecht** 2016-12-01 04:34 UTC
